### PR TITLE
Implement filterer for aggregated accounts

### PR DESCRIPTION
**Pull request by nhanaa**
@ncovercash  In the filter evaluator I used float as the common type to convert to before comparing the amounts and num rows. Is that good or is there a different preference? The evaluator should be in the #18bddfc commit.

### CODE REVIEW

**Comment by ncovercash** [comment]
@nhanaa I'd use `BigDecimal`; you can then use [it's `.compareTo` method](https://docs.oracle.com/javase/7/docs/api/java/math/BigDecimal.html#compareTo(java.math.BigDecimal))

**Comment by ncovercash** [comment]
@nhanaa my concern with `float` is that it can be imprecise, e.g. `0.1 + 0.2 ≠ 0.3` in float world. `BigDecimal` has more precision baked into that, I'd recommend either that or making everything `int`s.

**Comment by nhanaa** [comment]
@ncovercash I decided to use `int` as apart from totalAmount calculated from the account, everything else is `int` already.

**Review by ncovercash — APPROVED** [review]

**Comment by ncovercash** [comment]
Sounds great, int is the best for money since it doesn't get more precise than cents

**Pull request merged**
