### PR TITLE
fix bug: issue #148

### PR DESCRIPTION
**Pull request by GoZaddy**

### CODE REVIEW

**Review by ncovercash — APPROVED** [review]
Nice find!

**Comment by nhanaa** [comment]
@ncovercash The github action somehow fails but I'm not sure what the problem is. Is this concerning?

**Comment by ncovercash** [comment]
@nhanna I can't see it on my phone, but I'm guessing the unit test for this is failing (since it probably passed in the previous (incorrect) property). I'd go check and update the corresponding unit test

**Comment by GoZaddy** [comment]
> @Nhanna I can't see it on my phone, but I'm guessing the unit test for this is failing (since it probably passed in the previous (incorrect) property). I'd go check and update the corresponding unit test

Oh yeah, my bad. I'll go update that

**Review by ncovercash — APPROVED** [review]
lgtm, assuming this fixes test issue

**Review by nhanaa — APPROVED** [review]

**Pull request merged**
